### ISSUE TITLE
VCF in compress format (gz)

### ISSUE THREAD

**Issue by antonylebechec** [natir/variantplaner#11]
**Is your feature request related to a problem? Please describe.**
Ass many VCF are compressed in BGZip format, it could be great to deal with this format as input file (-i input.vcf.gz)

**Describe the solution you'd like**
An elegant solution!

**Describe alternatives you've considered**

**Additional context**

**Comment by natir** [comment]
As indicate in [Readme](https://github.com/natir/variantplaner/blob/main/README.md?plain=1#L26) compress file isn't yet support due to downstream library limitation [polars](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.scan_csv.html)

**Comment by natir** [comment]
This issue is relate to pola-rs/polars/issues/7287
