### ISSUE TITLE
New CLI

### ISSUE THREAD

**Issue by natir** [natir/variantplaner#33]
Results of the reflection that will be modified.

# variantplaner
- t, thread: only positive number
- v, verbose: repetition or positive number
- V, version: flag

Example:
```bash
variantplaner -t 6 -vvvv
```

## vcf2parquet:
- i, input: path to an existing vcf file
- a, append: flag, vcf2parquet became in append mode

Example:
```bash
vcf2parquet -i  input_path.vcf --apend
```

### variants
- o, output:  path where variants parquet be write

Example:
```bash
variants -o variants/input_path.parquet
```

### genotypes
- o, output: path where genotype parquet be write
- f, format: value of format column, line not match with this are ignored

Example:
```bash
genotypes -o genotypes/input_path.parquet
```

### annotations
- o, output: path where annotation parquet be write

Example:
```bash
annotations -o annotations/input_path.parquet
```

## struct
- i, inputs_paths: path of parquet should be structurate

Example:
```bash
struct -i variants/HG0002.parquet variants/HG0003.parquet
```

### genotypes
- p, prefix: prefix path of genotypes structuration
- t. type: type of structuration, possible value: real_position, random default: real_position
- n, number: number of part, default: 256

Example:
```bash
genotypes -p genotype_struct -t real_position 
```

### variants
- o, output: path to output
- c, chunk-size: sizes of files chunks that will be grouped together to build the list of unique variants (default: 1,000,000)
- p, polars-threads: number of threads use to merge a chunk of files (default: 4 positive number)

Example:
```bash
variants -o unique_variants.parquet 
```

## parquet2vcf
- v, variants: path to variants parquet
- g, genotype: path to genotype parquet
- a, annotation: path to annotation parquet
- o, output: path to vcf output
- c, chromosome: name of chromosome column  [default: chr]
- p, position: name of position column  [default: pos]
- i, identifier: name of identity column  [default: id]
- r, reference: name of reference column  [default: ref]
- A, alternative: name of alternative column  [default: alt]
- q, quality: name of quality column
- f, filter: name of filter column
- F, format: value of format column

Example:
```bash
parquet2vcf -v variants/FFFF.parquet -g genotypes/FFFF.parquet -a annotations/FFFF.parquet -o FFFF.vcf 
```

## transmission
- i, input-path: Path genotypes parquet file  [required]
- p, ped-path: Path to the ped file
- I, index: Sample name of index
- m, mother: Sample name of mother
- f, father: Sample name of father
- o, output-path: Path transmission mode will be store

Example:
```bash
transmission -i genotypes/FFFF.parquet -p FFFF.ped -o transmissions/FFFF.parquet
```

## metadata
- i, input_path: Path to input file
- o, output_path: Path to output file
- t, type: Type of file [ljson, csv]

Example:
```bash
metadata -i samples/FFFF.json -o samples/FFFF.parquet -t ljson

**Comment by natir** [comment]
Results of the reflection that will be modified.

# variantplaner
- t, thread: only positive number
- v, verbose: repetition or positive number
- V, version: flag

Example:
```bash
variantplaner -t 6 -vvvv
```

## vcf2parquet:
- i, input: path to an existing vcf file
- a, append: flag, vcf2parquet became in append mode

Example:
```bash
vcf2parquet -i  input_path.vcf --apend
```

### variants
- o, output:  path where variants parquet be write

Example:
```bash
variants -o variants/input_path.parquet
```

### genotypes
- o, output: path where genotype parquet be write
- f, format: value of format column, line not match with this are ignored

Example:
```bash
genotypes -o genotypes/input_path.parquet
```

### annotations
- o, output: path where annotation parquet be write

Example:
```bash
annotations -o annotations/input_path.parquet
```

## struct
- i, inputs_paths: path of parquet should be structurate

Example:
```bash
struct -i variants/HG0002.parquet variants/HG0003.parquet
```

###

**Comment by ehenrion** [comment]
Hello there,

Maybe a `-m, --memory` parameter would be nice as well (if possible) ;)

Thanks
Edouard
