### ISSUE TITLE
feature: Check chrom length within VCF header

### ISSUE THREAD

**Issue by antonylebechec** [natir/variantplaner#39]
### Is your feature request related to a problem? Please describe.
For vcf2parquet, option for chrom length is not easy to deal with.
```
option '-c' / '--chrom2length-path'.
```

### Describe the solution you'd like
Check within the VCF to obtain the chrom length (contigs), if exists

### Describe alternatives you've considered
None, yet.

### Additional context
NA

**Comment by natir** [comment]
Unfortunately, chromosome lines are not mandatory in VCF. A solution might be to make the chrom2length option not mandatory and if it's not present and chromosome lines are missing, raise an error.

Does that sound satisfying?

**Comment by antonylebechec** [comment]
That sounds good!
