### ISSUE TITLE
bug: Memory allocation failed

### ISSUE THREAD

**Issue by antonylebechec** [natir/variantplaner#40]
### Description of the bug
Memory allocation failed
I used a small VCF file, and chromlength.csv from https://raw.githubusercontent.com/natir/variantplaner/main/tests/data/grch38.92.csv

### To Reproduce
```
variantplaner vcf2parquet -i /tool/tests/data/example.vcf -v variants.parquet -g genotypes.parquet -a annotations.parquet -c chromlength.csv
```

### Full traceback
```
memory allocation of 9006383710622720 bytes failed
```

### Expected behavior
No bug...

### Environment information
Python 3.10.13
VariantPlaner 0.2.2

**Comment by natir** [comment]
Hello,

Sorry this bug occur previously on version 0.2.2 the solution is use dev version:
```
pip install git+https://github.com/natir/variantplaner.git#egg=variantplaner
```

A new release while probably release soon.

If it's solve your trouble please close this issues.
