### ISSUE TITLE
Question about "variantplaner struct genotypes"

### ISSUE THREAD

**Issue by ehenrion** [natir/variantplaner#44]
This is not a bug report but a simple question. :) 

I have a situation where I seem to have too many input files for the _`variantplaner struct genotypes`_ command...
Indeed, when doing the following 
```
input=$(ls genotypes_dir/samples | xargs -I {} -x echo "-i genotypes/samples/"{} | tr '\n' ' ')
```
I hit a `OSError: File name too long (os error 36)` error when running 
```
variantplaner -t 20 struct $(echo $input) genotypes -p genotypes/variants
```

So my question is : would I achieve the same result if I run the _`variantplaner struct genotypes`_ command on each of my files separately ? i.e 
```
variantplaner -t 20 struct -i file1.parquet genotypes -p genotypes/variants
variantplaner -t 20 struct -i file2.parquet genotypes -p genotypes/variants
variantplaner -t 20 struct -i file3.parquet genotypes -p genotypes/variants
variantplaner -t 20 struct -i file4.parquet genotypes -p genotypes/variants
...
```

Thanks for the clarification !

**Comment by ehenrion** [comment]
Actually this questoin applies to another case : if I am regularily adding new data, do I have to run the whole structuration again to include the new genotypes with
```
input=$(ls genotypes_dir/samples | xargs -I {} -x echo "-i genotypes/samples/"{} | tr '\n' ' ')
variantplaner -t 20 struct $(echo $input) genotypes -p genotypes/variants
```
or is there another way ?

Thanks a lot

**Comment by natir** [comment]
A simplified command line is already planned for version 0.3. But it is also planned to add sequential addition options to avoid having to recalculate the single variant base and the structuring of genotypes on all variants.

**Comment by ehenrion** [comment]
That's great news ! 
If you need any help on this, just let me know ! ;)
